name: colibri
description: Colibri


publish_to: 'none' 

version: 1.1.3+21

environment:
  sdk: '>=2.14.0 <3.0.0'

flutter_localizations:
    sdk: flutter

dependencies:
  flutter:
    sdk: flutter
  # for functional programming
  dartz: ^0.10.0
  # for api calls
  dio: ^4.0.0 
  google_fonts: ^2.1.0 
  flutter_hooks: ^0.18.0 

  flutter_screenutil: ^5.0.0+2 
  rxdart: ^0.27.1 
  flutter_svg: ^0.22.0 
  flutter_bloc: ^7.1.0 

  freezed: ^0.14.5
  freezed_annotation: ^0.14.3
  equatable: ^2.0.3 
  injectable: ^1.5.0
  get_it: ^7.2.0 
  another_flushbar: ^1.10.24
  font_awesome_flutter: ^9.1.0 
  cached_network_image: ^3.1.0
  image_picker: ^0.8.3+2 
  emoji_picker_flutter: ^1.0.7
  flutter_animated_dialog: ^2.0.1 
  giphy_picker: ^2.0.0
  intl: ^0.17.0
  auto_route: ^2.4.2
  photo_view: ^0.12.0
  file_picker: ^4.0.0 
  flutter_cache_manager: ^3.1.2
  path_provider: ^2.0.2 
  video_compress: ^3.1.0 
  flutter_easyloading: ^3.0.0 
  permission_handler: ^8.2.5
  better_player: ^0.0.76
  flutter_login_facebook: ^1.1.0
  google_sign_in: ^5.0.7 
  infinite_scroll_pagination: ^3.1.0 
  auto_size_text: ^3.0.0-nullsafety.0
  faker: ^2.0.0 
  native_device_orientation: ^1.0.0
  mime: ^1.0.0
  velocity_x: ^3.3.0
  timelines: ^0.1.0 
  url_launcher: ^6.0.9 
  animations: ^2.0.1 
  html_unescape: ^2.0.0 
  flutter_linkify: ^5.0.2 
  share: ^2.0.4
  webview_flutter: ^2.0.12 
  shared_preferences: ^2.0.8
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3 
  material_floating_search_bar: ^0.3.4
  flutter_local_notifications: ^8.1.1+1
  image_cropper: ^1.4.1 
  expandable_page_view: ^1.0.6 
  flutter_image_compress: ^1.1.0 
  #Discontinued
  file_utils: ^1.0.1
  keyboard_actions: ^3.4.3
  firebase_messaging: ^10.0.6
  firebase_core: ^1.5.0
  smart_select:
   git:
     url: https://github.com/iktakahiro/flutter_smart_select.git
     ref: null-safety
  remove_emoji: ^0.0.6 
  modal_bottom_sheet: ^2.0.0 
  easy_localization: ^3.0.0  
  html: ^0.15.0
  flutter_html: ^2.1.5
  simple_url_preview: ^3.0.1 
  youtube_player_flutter: ^8.0.0 
  flutter_keyboard_visibility: ^5.0.3
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  dependency_validator: ^3.0.0
  auto_route_generator: ^2.4.1
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"

flutter_native_splash:
  image: images/logo.png
  color: "#FFFFFF"
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  
  assets:
    - images/
    - images/png_image/
    - assets/translations/


  fonts:
#   
    - family: Campton
      fonts:
        - asset: fonts/Campton-Light.ttf
          weight: 200
        - asset: fonts/Campton-Medium.ttf
          weight: 400
        - asset: fonts/Campton-Bold.ttf
          weight: 600
    - family: CeraPro
      fonts:
        - asset: fonts/CeraPro-Regular.ttf
          weight: 200
        - asset: fonts/CeraPro-Medium.ttf
          weight: 400
        - asset: fonts/CeraPro-Bold.ttf
          weight: 600