name: colibri
description: Colibri


publish_to: 'none' 

version: 1.1.4+22

environment:
  sdk: ">=2.15.1 <3.0.0"

flutter_localizations:
    sdk: flutter

dependencies:
  flutter:
    sdk: flutter
  # for functional programming
  dartz: ^0.10.1
  # for api calls
  dio: ^4.0.4 
  google_fonts: 2.2.0
  flutter_hooks: ^0.18.2 
  # don't change this!
  flutter_screenutil: '5.1.0'
  rxdart: ^0.27.3 
  flutter_svg: ^1.0.3
  flutter_bloc: ^8.0.1

  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  equatable: ^2.0.3
  injectable: ^1.5.3
  get_it: ^7.2.0 
  another_flushbar: ^1.10.28
  font_awesome_flutter: ^9.2.0 
  cached_network_image: ^3.2.0
  image_picker: ^0.8.4+5 
  emoji_picker_flutter: ^1.1.1
  flutter_animated_dialog: ^2.0.1 
  giphy_picker: ^2.0.0
  intl: ^0.17.0
  auto_route: ^3.2.2
  photo_view: ^0.13.0
  file_picker: ^4.3.3 
  flutter_cache_manager: ^3.3.0
  path_provider: ^2.0.8 
  video_compress: ^3.1.0 
  flutter_easyloading: ^3.0.3
  permission_handler: ^8.3.0
  better_player: ^0.0.81
  flutter_login_facebook: ^1.2.1
  google_sign_in: ^5.2.3
  infinite_scroll_pagination: ^3.1.0 
  auto_size_text: ^3.0.0-nullsafety.0
  faker: ^2.0.0 
  native_device_orientation: ^1.0.0
  mime: ^1.0.1
  velocity_x: ^3.4.0
  timelines: ^0.1.0 
  url_launcher: ^6.0.18
  animations: ^2.0.2 
  flutter_linkify: ^5.0.2 
  share: ^2.0.4
  webview_flutter: ^3.0.0 
  shared_preferences: ^2.0.12
  visibility_detector: ^0.2.2
  cupertino_icons: ^1.0.4
  material_floating_search_bar: ^0.3.6
  flutter_local_notifications: ^9.2.0
  image_cropper: ^1.4.1 
  flutter_image_compress: ^1.1.0 
  #Discontinued
  file_utils: ^1.0.1
  keyboard_actions: ^3.4.6
  firebase_messaging: ^11.2.6
  firebase_core: ^1.12.0
  awesome_select: ^5.1.0
  remove_emoji: ^0.0.6 
  modal_bottom_sheet: ^2.0.0 
  easy_localization: ^3.0.0  
  html: ^0.15.0
  simple_url_preview: ^3.0.1 
  youtube_player_flutter: ^8.0.0 
  flutter_keyboard_visibility: ^5.1.1
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  dependency_validator: ^3.1.2
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"

flutter:
  uses-material-design: true

  
  assets:
    - images/
    - images/png_image/
    - assets/translations/


  fonts:
#   
    - family: Campton
      fonts:
        - asset: fonts/Campton-Light.ttf
          weight: 200
        - asset: fonts/Campton-Medium.ttf
          weight: 400
        - asset: fonts/Campton-Bold.ttf
          weight: 600
    - family: CeraPro
      fonts:
        - asset: fonts/CeraPro-Regular.ttf
          weight: 200
        - asset: fonts/CeraPro-Medium.ttf
          weight: 400
        - asset: fonts/CeraPro-Bold.ttf
          weight: 600